### ISSUE TITLE
Unable to handle specific while format

### ISSUE THREAD

**Issue by streambinder** [bemeurer/beautysh#23]
It seems this executable is unable to handle `while` loops formatted as below:
```sh
while read -r thing; do
	echo "thing done"
done <<< $filename # or command
```

As soon as I remove those `<<<`, `beautysh` is behaving perfectly, as expected.

**Comment by bemeurer** [comment]
This is a known issue, with no solution currently.

**Comment by streambinder** [comment]
Tested patch. Waiting for approval.

**Comment by bemeurer** [comment]
Merged, thanks for the fix! I'll make a new release later today
