### ISSUE TITLE
Feature: Add check mode

### ISSUE THREAD

**Issue by thnee** [bemeurer/beautysh#27]
Would be useful if it could just verify if something would change, without actually changing the files. So that it can be used as part of a test suite.

See the `--check` flag in [black](https://github.com/ambv/black) for comparison.

It could print something like "x number of changes would be made to file zzz", and exit with 0 if there are no changes, and exit with 1 if there are changes.

**Comment by f18m** [comment]
I'd love to have this feature as well

**Comment by bemeurer** [comment]
@thnee, @f18m Has graciously gone ahead and implemented this, I've been overloaded with work lately. Please test it on the master branch!

**Comment by f18m** [comment]
Sorry @bemeurer but I think that by mistake commit #258330f has removed the --check option previously checked in. My bad.
Do you want me to resubmit the PR for the --check option?

**Comment by bemeurer** [comment]
@f18m No worries, please re-submit it :+1:
