### ISSUE TITLE
Example in readme has not a valid syntax

### ISSUE THREAD

**Issue by nesro** [bemeurer/beautysh#5]
Just a minor comment regarding your example of bash's ambiguous syntax. It's not a valid code:

```
bash-4.3$ bash -n <<< "echo done;done"
bash: line 1: syntax error near unexpected token `done'
bash: line 1: `echo done;done'
```

And even other parser, Bashlex, returns "unexpected token 'done'".

I'd love to see some example where is Beautysh failing on a valid code if there is any.

Thanks!

**Comment by bemeurer** [comment]
@nesro Ha, nice catch! Indeed the example is not valid. I'm searching online for some horrible bash code to put in it's place. If you find something let me know.
